type = "checkout_ui_extension"
name = "custom-fields-react"

# [START custom_field-react.step_3_1]
extension_points = [
  'Checkout::ShippingMethods::RenderAfter'
]
# [END custom_field-react.step_3_1]
