type = "checkout_ui_extension"
name = "custom-fields-react"

# [START custom_fields-react.ext-config]
extension_points = [
  'Checkout::ShippingMethods::RenderAfter'
]
# [END custom_fields-react.ext-config]

# liz do I need this
# [[metafields]]
# namespace = "yourAppNamespace"
# key = "deliveryInstructions"
