type = "checkout_ui_extension"
name = "product-offer-pre-purchase-js"

# [START product_offer-pre_purchase-js.step_2_1]
extension_points = [
  'Checkout::Dynamic::Render'
]
# [END product_offer-pre_purchase-js.step_2_1]

# [START product_offer-pre_purchase-js.step_3]
[capabilities]
api_access = true
# [END product_offer-pre_purchase-js.step_3]
