type = "checkout_ui_extension"
name = "product-offer-pre-purchase-js"

# [START product_offer-pre_purchase-js.ext-config]
extension_points = [
  'Checkout::Dynamic::Render'
]
# [END product_offer-pre_purchase-js.ext-config]

# [START product_offer-pre_purchase-js.api-access]
[capabilities]
api_access = true
# [END product_offer-pre_purchase-js.api-access]
