type = "checkout_ui_extension"
name = "product-offer-pre-purchase-react"

extension_points = [
  'Checkout::Dynamic::Render'
]

# [START product_offer-pre_purchase-react.sec_1-step_2]
[capabilities]
api_access = true
# [END product_offer-pre_purchase-react.sec_1-step_2]